### PR TITLE
Bug - fix case of bundle products without options

### LINKED ISSUE #566: Price building will fail when indexing bundle product without options
**Magento 2 version(s) used**: x.y.z
**Extension version(s) affected**: x.y.z

**Description**  
When a product bundle without option is indexed, it will be added in the indexing table and fail building the price as it has no options.

**How to reproduce**  

**Magento 2 mode**
- [ ] Developer 
- [ ] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  

**Additional context**

### PR DESCRIPTION
**Pull request by olsi-qose**
## Description
When a product bundle without option is indexed, it will be added in the indexing table and fail building the price as it has no options.

## Related Issue
closes #566

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have assigned the correct milestone or created one if non-existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [x] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Model/Service/Index.php [hunk 1]
```diff
@@ -269,6 +275,21 @@ public function updateOrCreateDirtyEntity(ProductInterface $product, StoreInterf
...
+     * @param ProductInterface $product
+     * @return bool
+     */
+    private function canNostoBuildProduct(ProductInterface $product)
+    {
+        if ($product->getTypeId() === Type::TYPE_BUNDLE && empty($product->getOptions())) {
+            return false;
+        }
+        return true;
+    }
```
Comment (supercid) [inline Model/Service/Index.php]: I'd rename this to `canBuildBundleProduct`
