### PR TITLE
Hotfix/3.7.2 -  Fix wrong store issue when connecting account

### LINKED ISSUE #460: Fix wrong store issue when connecting existing account

### PR DESCRIPTION
**Pull request by olsi-qose**
## Description
Get current store trying to connect the account from store code, which is provided as a url parameter `?___store`

## Related Issue
closes #460

## Motivation and Context
Some merchant are having issues when connecting Nosto account, it get connected to the wrong store. 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have assigned the correct milestone or created one if non existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [x] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Controller/Oauth/Index.php [hunk 1]
```diff
@@ -131,7 +134,14 @@ public function getMeta()
     public function save(AccountInterface $account)
     {
         $stores = $this->storeRepository->getList();
-        $currentStore = $this->nostoHelperScope->getStore();
+        $storeCode = $this->request->getParam('___store');
```
Comment (hannunosto) [inline Controller/Oauth/Index.php]: Use constant (https://github.com/Nosto/nosto-magento2/blob/develop/Helper/Url.php#L72) for the store parameter
