### PR TITLE
Resolve all IDE and Phan inspection warnings

### LINKED ISSUE #565: Fix IDE and Phan inspections
Fix all PHPStorm and Phan inspections that are failing.

### PR DESCRIPTION
**Pull request by mridang**
## Description
- Resolve all IDE and Phan inspections locally;
- Speedup Phan execution;

## Related Issue
Closes #565

## Motivation and Context
Many inspections are throwing warnings at the IDE, this PR fixes them so we have a clear view of what our changes can introduce.

## How Has This Been Tested?
- Tested locally with Magento 2.3.1

## Documentation:
N/A

## Checklist:
- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] I have assigned the correct milestone or created one if non-existent.
- [X] I have correctly labeled this pull request.
- [X] I have linked the corresponding issue in this description.
- [X] I have updated the corresponding Jira ticket.
- [X] I have requested a review from at least 2 reviewers
- [X] I have checked the base branch of this pull request
- [X] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Model/Indexer/AbstractIndexer.php [hunk 1]
```diff
@@ -125,18 +125,19 @@ public function __construct(
...
         $userFunctions = [];
 
         switch ($this->getModeSwitcher()->getMode()) {
             case DimensionModeConfiguration::DIMENSION_NONE:
+                /** @var Dimension[] $dimension */
                 foreach ($this->dimensionProvider->getIterator() as $dimension) {
                     if ($this->isDimensionProcessable($dimension)) {
-                        /** @suppress PhanTypeMismatchArgument */
-                        $this->executeByDimensions($dimension, new ArrayIterator($ids));
+                        (function () use ($dimension, $ids) {
```
Comment (mridang) [inline Model/Indexer/AbstractIndexer.php]: Please sanity check this.

Comment (supercid) [reply Model/Indexer/AbstractIndexer.php]: It works fine, but I can't suppress the issue since it's in a closure. (Only phan >0.12.x can suppress those)
The thing is that `getIterator` returns a generator that yields an array. But the function itself has a typehint to `\Traversable`

File: Model/Customer/Repository.php [hunk 2]
```diff
@@ -36,18 +36,16 @@
...
 use Magento\Framework\Exception\AlreadyExistsException;
 use Nosto\Tagging\Api\CustomerRepositoryInterface;
 use Nosto\Tagging\Api\Data\CustomerInterface;
-use Nosto\Tagging\Model\RepositoryTrait;
+use Nosto\Tagging\Model\Customer\Customer as NostoCustomer;
 use Nosto\Tagging\Model\ResourceModel\Customer as CustomerResource;
 use Nosto\Tagging\Model\ResourceModel\Customer\CollectionFactory as CustomerCollectionFactory;
 use Nosto\Tagging\Util\Repository as RepositoryUtil;
-use /** @noinspection PhpUnusedAliasInspection */
-    Nosto\Tagging\Model\Customer\CustomerSearchResults;
```
Comment (olsi-qose) [inline Model/Customer/Repository.php]: Why was this removed?

Comment (supercid) [reply Model/Customer/Repository.php]: The file is in the same directory, so we don't need the import.

File: Model/Item/Simple.php [hunk 3]
```diff
@@ -37,9 +37,54 @@
...
+use Throwable;
 
 class Simple
 {
+    /**
+     * @param ExtensibleDataInterface|SalesItem|Item $item
+     * @param $parentIds
+     * @return string|null
+     */
+    public static function buildName(ExtensibleDataInterface $item, $parentIds)
```
Comment (hannunosto) [inline Model/Item/Simple.php]: `ExtensibleDataInterface` doesn't really have `getName`, `getBuyRequest`, etc. methods.

Comment (supercid) [reply Model/Item/Simple.php]: True. I'll throw an exception
