### PR TITLE
Remove array constructor comparison from recobuy addMultipleProductsT…

### LINKED ISSUE #534: AddMultipleProductsToCart array check does not work from targeWindow
**Magento 2 version(s) used**: x.y.z
**Extension version(s) affected**: x.y.z

**Description**  
When passing an array of objects to `recobuy.addMultipleProductsToCart()` theres an array constructor check that fails since comes from another window.

**How to reproduce**  
Add this template to a recommendation slot and try to add any product to cart:
https://gist.github.com/supercid/a1b8fff164db5abd2c418385c1b36db3

**Magento 2 mode**
- [X] Developer 
- [X] Production

**Full page cache**
- [X] Enabled 
- [X] Disabled

**Nosto indexer mode**
- [X] Update On Save  
- [X] Update By Schedule

**Possible Solution**  
Remove check or check with `Array.isArray(obj)`.

**Additional context**

### PR DESCRIPTION
**Pull request by supercid**
## Description
Remove array constructor comparison from recobuy addMultipleProductsToCart. This does not work from one target window to another.
As a reference, see:
https://stackoverflow.com/questions/28467266/can-i-use-obj-constructor-array-to-test-if-object-is-array/28467392#28467392

## Related Issue
Fixes #534

## Motivation and Context
Some merchants using bundle recommendation slots are having issues adding them to cart from our reco slots.

## How Has This Been Tested?
Tested both in plugintest environment and locally using this template:
https://gist.github.com/supercid/a1b8fff164db5abd2c418385c1b36db3

## Documentation:
Unchanged

## Checklist:
- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] I have assigned the correct milestone or created one if non-existent.
- [X] I have correctly labeled this pull request.
- [X] I have linked the corresponding issue in this description.
- [X] I have updated the corresponding Jira ticket.
- [X] I have requested a review from at least 2 reviewers
- [X] I have checked the base branch of this pull request
- [X] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: view/frontend/web/js/recobuy.js [hunk 1]
```diff
@@ -55,11 +55,9 @@ define([
     // Products must be and array of objects [{'productId': '123', 'skuId': '321'}, {...}]
     // skuId is optional for simple products.
     Recobuy.addMultipleProductsToCart = function (products, element) {
-        if (products.constructor === Array) {
-            products.forEach(function (productObj) {
-                Recobuy.addSkuToCart(productObj, element, 1);
-            });
-        }
+        products.forEach(function (productObj) {
```
Comment (hannunosto) [inline view/frontend/web/js/recobuy.js]: We need to check if `products` has `forEach` method
