### PR TITLE
Hotfix 6.0.4 - Avoid multiple entries for the same customer on nosto_tagging_customer table

### LINKED ISSUE #512: Visitor and cart checksum tagging doesn't work when Nosto cookies are deleted
**Magento 2 version(s) used**: all
**Extension version(s) affected**: all

**Description**  
Nosto cart and customer checksum is not reset if Nosto cookies are cleared.

**How to reproduce**  

1. Open any product page and add the product to cart
2. Clear the Nosto cookies
3. Old checksum is still present in tagging 

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [x] Disabled

**Nosto indexer mode**
- [x] Update On Save  
- [x] Update By Schedule

**Possible Solution**  
Ditch the hcid tagging all together. It's only needed for preventing FPC to cache the checksums and in M2 customer tagging and cart tagging are using sections and those are cached only for the current session.

### PR DESCRIPTION
**Pull request by supercid**
## Description
Fixes #512

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I have assigned the correct milestone or created one if non-existent.
- [ ] I have correctly labeled this pull request.
- [ ] I have linked the corresponding issue in this description.
- [ ] I have updated the corresponding Jira ticket.
- [ ] I have requested a review from at least 2 reviewers
- [ ] I have checked the base branch of this pull request
- [ ] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Model/ResourceModel/Customer.php [hunk 1]
```diff
@@ -50,6 +50,6 @@ class Customer extends AbstractDb
      */
     public function _construct()
     {
-        $this->_init(self::TABLE_NAME, CustomerInterface::CUSTOMER_ID);
+        $this->_init(self::TABLE_NAME, CustomerInterface::ID);
```
Comment (supercid) [inline Model/ResourceModel/Customer.php:53]: That's the new table primary key. CustomerID should have magento customer ID and not some random autogenerated number like it was before

File: Model/Customer/Customer.php [hunk 2]
```diff
@@ -91,7 +91,7 @@ public function getUpdatedAt()
     /**
      * @inheritDoc
      */
-    public function setCustomerId(int $customerId)
+    public function setCustomerId(?int $customerId)
```
Comment (supercid) [inline Model/Customer/Customer.php:94]: Can be null now, since the customer can be not_logged_in and only afterwards log in/create account

File: Model/Cart/Restore/Builder.php [hunk 3]
```diff
@@ -112,35 +118,45 @@ public function build(Quote $quote, Store $store)
...
-        } else {
+            $nostoCustomer->setNostoId($nostoCustomerId);
+        } else { // Create a new entry
             $nostoCustomer = $this->nostoCustomerFactory->create();
             $nostoCustomer->setQuoteId($quote->getId());
             $nostoCustomer->setNostoId($nostoCustomerId);
             $nostoCustomer->setCreatedAt($this->getNow());
             $nostoCustomer->setRestoreCartHash($this->generateRestoreCartHash());
+            if ($mageCustomerId) {
+                $nostoCustomer->setCustomerId($mageCustomerId);
```
Comment (supercid) [inline Model/Cart/Restore/Builder.php:155]: Case where customer only added to cart after logging in

File: Model/Cart/Restore/Builder.php [hunk 4]
```diff
@@ -188,4 +204,26 @@ private function generateRestoreCartUrl(string $hash, Store $store)
         $params['h'] = $hash;
         return $store->getUrl(NostoHelperUrl::NOSTO_PATH_RESTORE_CART, $params);
     }
+
+    /**
+     * @param string $nostoCustomerId
+     */
+    private function deleteOldEntries(string $nostoCustomerId): void
```
[the remark this answers is not in the document]
Comment (supercid) [reply Model/Cart/Restore/Builder.php:211]: Or used the restore to cart link and only then logged in

**Review by olsi-qose — APPROVED** [review]
