### PR TITLE
Hotfix/3.0.4

### LINKED ISSUE #385: Attribute tags to custom fields fails if no attributes are tagged for tags2 and tags3
`$attributes` variable will be null if there are no attributes defined to be tagged for tags2 and / or tags3: 
https://github.com/Nosto/nosto-magento2/blame/develop/Model/Product/Builder.php#L326

### PR DESCRIPTION
**Pull request by olsiqose-nosto**
## Description
Use a new variable for tag attributes in method getCustomFieldsWithAttributes() in Product/Builder.php

## Related Issue
closes #385

## Motivation and Context
Merchant faced an issue when custom attributes were added to tag1 or tag2, they were not added to custom_fields as the variable holding those values would be re-initialised in a for loop.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have assigned the correct milestone or created one if non existent.
- [ ] I have correctly labeled this pull request.
- [ ] I have linked the corresponding issue in this description.
- [ ] I have updated the corresponding Jira ticket.
- [ ] I have requested a review from at least 2 reviewers

### CODE REVIEW

File: Model/Product/Builder.php [hunk 1]
```diff
@@ -358,9 +359,20 @@ private function amendAttributeTags(Product $product, NostoProduct $nostoProduct
                     if (empty($attributeValue)) {
                         continue;
                     }
-                    //addTag1(), addTag2() and addTag3() are called
-                    $addTagMethodName = 'add' . $tag;
-                    $nostoProduct->$addTagMethodName(sprintf('%s:%s', $productAttribute, $attributeValue));
+
+                    switch ($tag) {
+                        case 'tag1':
```
Comment (hannunosto) [inline Model/Product/Builder.php]: We should add constants for these into the SDK. I suppose we would do similar changes than this to other plugins as well.

Comment (hannunosto) [reply Model/Product/Builder.php]: Let's do this later
