### PR TITLE
Fix product URL building for product

### LINKED ISSUE #54: Editing product in magento leads to broken product url in Nosto
This problem happened in Magento EE 2.1.5 plugin version 1.2.0

### PR DESCRIPTION
**Pull request by mridang**
Closes #54

### CODE REVIEW

File: Model/Product/Url/Builder.php [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+        array $data = []
+    ) {
+        parent::__construct($data);
+        $this->data = $data;
+        $this->filter = $filter;
+        $this->urlFinder = $urlFinder;
+        $this->urlFactory = $urlFactory;
+    }
+
+    public function getUrlInStore(Product $product, $storeId)
```
Comment (hannunosto) [inline Model/Product/Url/Builder.php]: I would pass StoreInterface instead of int (`$storeId`) to have more type safety
