### PR TITLE
Fix bundled product price determination when all products are optional 

### LINKED ISSUE #231: Bundle product list price is tagged incorrectly
Bundle product list price is tagged incorrectly. If the option is optional, than is should not be included to the min price. But if all the options are optional, the cheapest option should be take for the price.

### PR DESCRIPTION
**Pull request by hannunosto**
Use the cheapest option price for bundled product if all products in bundle are optional

closes #231

### CODE REVIEW

File: Helper/Price.php [hunk 1]
```diff
@@ -124,23 +124,36 @@ public function getProductPrice( // @codingStandardsIgnoreLine
...
+                                $requiredMinPrices[] = $selectionMinPrice;
+                            }
                         }
+                        // If all products are optional use the price for the cheapest option
+                        if ($allOptional) {
+                            asort($minPrices);
+                            $sorted = array_values($minPrices);
+                            $listPrice = !empty($sorted[0]) ? $sorted[0] : null;
+                        } else {
+                            $listPrice = array_sum($minPrices);
```
Comment (chenliangde) [inline Helper/Price.php]: Should be $requiredMinPrices

File: Helper/Price.php [hunk 2]
```diff
@@ -124,23 +124,36 @@ public function getProductPrice( // @codingStandardsIgnoreLine
...
+                            if ($option->getRequired()) {
+                                $allOptional = false;
+                                $requiredMinPrices[] = $selectionMinPrice;
+                            }
                         }
+                        // If all products are optional use the price for the cheapest option
+                        if ($allOptional) {
+                            asort($minPrices);
+                            $sorted = array_values($minPrices);
+                            $listPrice = !empty($sorted[0]) ? $sorted[0] : null;
```
Comment (chenliangde) [inline Helper/Price.php]: How about this: http://php.net/manual/en/function.min.php

File: Helper/Price.php [hunk 3]
```diff
@@ -124,23 +124,36 @@ public function getProductPrice( // @codingStandardsIgnoreLine
...
-                                } catch (\Exception $e) {
-                                    $this->_logger->error($e->__toString());
+                        $options = $productType->getOptions($product);
+                        $allOptional = true;
+                        $minPrices = [];
+                        $requiredMinPrices = [];
+                        foreach ($options as $option) {
+                            $selectionMinPrice = null;
+                            /* @var Product $selection */
+                            foreach ($option->getSelections() as $selection) {
```
Comment (chenliangde) [inline Helper/Price.php]: I am not sure about magento2. But in magento1, if the option is not available( out of stock), than it is not being considering in the price calculation. https://github.com/Nosto/nosto-magento/pull/377/files#diff-de1e1ce4da97152934687e9a89a70a04R267

Comment (hannunosto) [reply Helper/Price.php]: I tested this and if an selection (sku) is not available or is out of stock it will not be returned when calling `getSelections()`

Comment (chenliangde) [reply Helper/Price.php]: Ok. May be we don't have to check it in magento1 as well.
