### PR TITLE
Hotfix - 3.8.1

### LINKED ISSUE #485: Data upgrades do not run when upgrading from an old version
**Magento 2 version(s) used**: 2.1.7
**Extension version(s) affected**: <3.1.0 & <3.5.0

**Description**  
When updating the module from an old version (anything before 3.1.0) to the latest version, the migrations in `Nosto\Tagging\Setup\UpgradeData` do not get run because the version check is using the incorrect comparison operator. This means that the store domain does not get stored in `core_config_data` table, causing a warning in Magento backend, and the customer reference attribute does not get added.

**How to reproduce**  
1. Install module version 3.0.3
2. Run `bin/magento setup:upgrade`
3. Configure Nosto in Magento Backend
4. Install module version 3.7.4
5. Run `bin/magento setup:upgrade`

***Expected outcome:***
After running the upgrade, the store domain should be set in the `nosto_tagging/settings/domain` setting in `core_config_data`, and a new customer attribute `nosto_customer_reference` should be created.

***Actual outcome:***

The store domain is not set, and customer attribute is missing.

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [ ] Enabled 
- [ ] Disabled

**Nosto indexer mode**
- [ ] Update On Save  
- [ ] Update By Schedule

**Possible Solution**  
The comparison operator used in the `version_compare` function in `Nosto\Tagging\Setup\UpgradeData` should be `<=` instead of `>=`. The version provided by the `$context` object in that class is the current version in the database, not current version in the module files, so when upgrading from a really old version (e.g. `3.0.3`), neither of the `if` statements passes.

**Additional context**

### PR DESCRIPTION
**Pull request by olsi-qose**
## Description
Version comparison in `UpgradeData.php` script was wrong, so when the module would get upgraded the methods within the if statements did not run.

## Related Issue
closes #485 

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have assigned the correct milestone or created one if non-existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [x] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Setup/UpgradeData.php [hunk 1]
```diff
@@ -87,11 +87,12 @@ public function __construct(
      */
     public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context) // @codingStandardsIgnoreLine
     {
-        if (version_compare($context->getVersion(), '3.1.0', '>=')) {
+        $currentVersion = $context->getVersion();
```
Comment (hannunosto) [inline Setup/UpgradeData.php]: To avoid confusion in future how about renaming this to `$fromVersion`
