### PR TITLE
Move setArea call outside of construct to avoid LocalizedException is…

### LINKED ISSUE #96: Module causes LocalizedException with other module that setAreaCode
`Console/Command/SyncProducts.php` calls `$state->setAreaCode(Area::AREA_FRONTEND);` in the constructor. Instances of all command classes for all modules are initialized in Magento 2 when **any** command is run so this construct level set causes of the area code  issues as the are code can only be set once.

A `LocalizedException` is thrown with any other module commands try to set the area code at any point. The recommendation is seem to be to set the area outside the construct. This avoids conflict with other modules commands.

```
                                                    
  [Magento\Framework\Exception\LocalizedException]  
  Area code is already set                          
                                                
```    

Similar to : 
[https://github.com/Iazel/magento2-regenurl/pull/15/files](https://github.com/Iazel/magento2-regenurl/pull/15/files)

Magento 2.1.5

### PR DESCRIPTION
**Pull request by davefarthing**
Moving the setArea outside of the construct avoids conflict with other CLI commands the need to setArea.  Closes #96

### CODE REVIEW

File: Console/Command/SyncProducts.php [hunk 1]
```diff
@@ -137,6 +136,10 @@ public function configure()
      */
     public function execute(InputInterface $input, OutputInterface $output)
     {
+        if (!$this->state->getAreaCode()) {
```
Comment (uabassguy) [inline Console/Command/SyncProducts.php]: Use a try catch block
