### PR TITLE
Hotfix - Product availability on single store mode

### LINKED ISSUE #502: Products With Invisible Availability When Single Store Mode Is Enabled
**Magento 2 version(s) used**: 2.2-2.3
**Extension version(s) affected**: All

**Description**  
When single-store mode is enabled, product availability is always set to `Invisible`

**How to reproduce**  
Enable single store mode and check product availability on the tagging.
screenshot-2

**Magento 2 mode**
- [x] Developer 
- [x] Production

**Full page cache**
- [x] Enabled 
- [x] Disabled

**Nosto indexer mode**
- [x] Update On Save  
- [x] Update By Schedule

**Possible Solution**  
Add an extra check on `buildAvailability();` where call the store ID. There's probably a constant store ID for single store mode.

### PR DESCRIPTION
**Pull request by supercid**
## Description
Fixes Products build availability when in single store mode.
## Related Issue
Fixes #502 

## Motivation and Context
When using Magento in single store mode, all products are marked as Invisible, this PR fix this issue

## How Has This Been Tested?
Locally With Magento 2.3 with:
- [X] Configurable products and its SKU's;
- [X] Single Products;
- [X] Grouped Products.

## Documentation:
N/A

## Checklist:
- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] I have assigned the correct milestone or created one if non-existent.
- [X] I have correctly labeled this pull request.
- [X] I have linked the corresponding issue in this description.
- [X] I have updated the corresponding Jira ticket.
- [X] I have requested a review from at least 2 reviewers
- [X] I have checked the base branch of this pull request
- [X] I have checked my code for any possible security vulnerabilities

### CODE REVIEW

File: Model/Product/Builder.php [hunk 1]
```diff
@@ -397,7 +401,7 @@ private function buildAvailability(Product $product, Store $store)
     {
         $availability = ProductInterface::OUT_OF_STOCK;
         if (!$product->isVisibleInSiteVisibility()
-            || !$this->isAvailabeInStore($product, $store)
+            || (!$this->isAvailableInStore($product, $store) && $this->isInStock($product, $store))
```
Comment (hannunosto) [inline Model/Product/Builder.php]: Why do we need `$this->isInStock($product, $store)` here? I'd at least extract this into a variable since it's used later on as well.

Comment (supercid) [reply Model/Product/Builder.php]: Cause `isAvailableInStore` doesn't take into account `outOfStock` items. They can be either. By checking if is `outOfStock` we prevent to mark all of them as invisible when, in fact, they are `outOfStock`
