### PR TITLE
Fix the discount handling for ordered items

### LINKED ISSUE #145: Fix the discount calculation for ordered items

### PR DESCRIPTION
**Pull request by hannunosto**
* base discount must be divided by the ordered quantity
* closes #145

### CODE REVIEW

File: Model/Order/Item/Builder.php [hunk 1]
```diff
@@ -93,7 +93,13 @@ public function build(Item $item)
                 break;
         }
         try {
-            $price = $item->getBasePrice() + $item->getBaseTaxAmount() - $item->getBaseDiscountAmount();
+            if ($item->getBaseDiscountAmount() > 0) {
+                // baseDiscountAmount contains the discount for the whole row
+                $lineDiscount = $item->getBaseDiscountAmount()/$item->getQtyOrdered();
+            } else {
```
Comment (mridang) [inline Model/Order/Item/Builder.php]: Put the `lineDiscount` outside the clause.
